### ISSUE TITLE
Centered Picture component

### ISSUE THREAD

**Issue by CristianStrit** [TastingKitchen/tasting-kitchen#11]
The Picture of the landscape should be a centered picture component and the cutline below should be:

color: #787276;
font-family: Inter;
font-size: 10px;
font-style: italic;
text-align: center;

<img width="965" alt="Screen Shot 2020-06-29 at 10 53 22 PM" src="https://user-images.githubusercontent.com/67622271/86088799-d82f7300-ba5b-11ea-94a7-06d085381209.png">

**Comment by erkgmz** [comment]
@CristianStrit Are the cutline styles the same for mobile as well?

**Comment by CristianStrit** [comment]
on mobile the style is the same but size is a bit larger

  color: #787276;
  font-family: Inter;
  font-size: 13px;
  font-style: italic;
  letter-spacing: 0;
  line-height: 18px;
  text-align: center;

<img width="396" alt="Screen Shot 2020-06-29 at 11 54 16 PM" src="https://user-images.githubusercontent.com/67622271/86093608-192b8580-ba64-11ea-8b09-16182b191a43.png">

**Comment by erkgmz** [comment]
Ok, I applied a global treatment for cutlines. 
375+ font-size: 13px
834+ font-size: 10px
