### ISSUE TITLE
Please check the spacing problems between components 

### ISSUE THREAD

**Issue by CristianStrit** [TastingKitchen/tasting-kitchen#12]
See image bellow for correct spacing
<img width="1101" alt="Screen Shot 2020-06-29 at 10 59 51 PM" src="https://user-images.githubusercontent.com/67622271/86089137-7faca580-ba5c-11ea-8eb5-c8df50eec532.png">

**Comment by erkgmz** [comment]
Note to self: Remove top/bottom padding from Quote component

**Comment by erkgmz** [comment]
@CristianStrit The components padding has been removed. This was caused by the new spacers we added.
