### ISSUE TITLE
Wrong image size

### ISSUE THREAD

**Issue by CristianStrit** [TastingKitchen/tasting-kitchen#13]
This image should not fill the page. Please follow the specs on the Italy article in InVision.

<img width="965" alt="Screen Shot 2020-06-29 at 11 08 15 PM" src="https://user-images.githubusercontent.com/67622271/86090760-8c7ec880-ba5f-11ea-9808-99e51ce78e77.png">

**Comment by erkgmz** [comment]
This is a content update in Wordpress and should be fixed now.  Please check @CristianStrit

**Comment by CristianStrit** [comment]
ok

**Comment by erkgmz** [comment]
@CristianStrit please review this again. Close this Issue once you've confirmed the fix.
