### ISSUE TITLE
Wrong image sizes and layout

### ISSUE THREAD

**Issue by CristianStrit** [TastingKitchen/tasting-kitchen#14]
Please follow the specs for these two side-by-side images.

<img width="964" alt="Screen Shot 2020-06-29 at 11 28 52 PM" src="https://user-images.githubusercontent.com/67622271/86091238-6148a900-ba60-11ea-9fca-5780bd8eb3d8.png">

<img width="964" alt="Screen Shot 2020-06-29 at 11 29 00 PM" src="https://user-images.githubusercontent.com/67622271/86091226-5d1c8b80-ba60-11ea-8afa-975aa967befc.png">

**Comment by erkgmz** [comment]
@CristianStrit Were currently using the size of the images to set the container height. Do you want me to hard code the height and width or should we update the asset?

**Comment by CristianStrit** [comment]
no, maybe this is an asset problem I need to look at the CMS and re-upload new assets

**Comment by erkgmz** [comment]
Consider adding the ability to flip the order (vertical & horizontal <or> horizontal & vertical)

**Comment by erkgmz** [comment]
> Consider adding the ability to flip the order (vertical & horizontal horizontal & vertical)

@CristianStrit we can acheive this based on the upload order in CMS so I'll only focus on the issues with the height.

**Comment by erkgmz** [comment]
@CristianStrit the height of the tall image is ~800px, which is causing the distortion.
![image](https://user-images.githubusercontent.com/8197799/86203366-b0064980-bb19-11ea-912f-f95224726b5e.png)

If you want, I can set a max-height on the img directly, here's what it looks like at 500px (vertically/horizontally centered and cropped)
![image](https://user-images.githubusercontent.com/8197799/86203431-d926da00-bb19-11ea-9222-901ed2b70ca3.png)

Let me know your thoughts.

**Comment by CristianStrit** [comment]
I think the dimensions that you're seeing from the photo (834w x 1214h) is 2x. So we'll have to divide that by half at: 417w x 607h. Also for some reason it seems like the photo aspect ratio has switched between the two. The right side should be a vertical layout and the left side should be a horizontal layout – based on the photos that I had uploaded.

<img width="922" alt="Screen Shot 2020-07-01 at 9 38 05 AM" src="https://user-images.githubusercontent.com/67622271/86269490-aa8f1a80-bb7e-11ea-99c5-f75464f49250.png">

**Comment by erkgmz** [comment]
The actual dimensions are 593 x 863, can you reduce the the height down to the range it should be on?

**Comment by CristianStrit** [comment]
I just uploaded a 1x version of the images and the component is doing the same scaling and cropping thing. I don't think is a problem of the image that I'm uploading.

<img width="1500" alt="Screen Shot 2020-07-01 at 10 49 28 PM" src="https://user-images.githubusercontent.com/67622271/86321242-730b8700-bbed-11ea-88cf-da5fa4af86d4.png">
<img width="1085" alt="Screen Shot 2020-07-01 at 10 47 53 PM" src="https://user-images.githubusercontent.com/67622271/86321256-7b63c200-bbed-11ea-9257-9bc311fbc64a.png">
<img width="1069" alt="Screen Shot 2020-07-01 at 10 48 05 PM" src="https://user-images.githubusercontent.com/67622271/86321257-7bfc5880-bbed-11ea-9d38-a576c349ee7a.png">

**Comment by erkgmz** [comment]
@CristianStrit No max-height neccessary!

Just make sure to upload the images in this order and you should be good.

LANDSCAPE | PORTRAIT
