### ISSUE TITLE
Wrong image size and layout

### ISSUE THREAD

**Issue by CristianStrit** [TastingKitchen/tasting-kitchen#15]
Wrong image size and should not be full screen.
Please check specs and layout in InVision. 

<img width="968" alt="Screen Shot 2020-06-29 at 11 30 51 PM" src="https://user-images.githubusercontent.com/67622271/86091451-cb614e00-ba60-11ea-83c7-f07e60078ff0.png">

**Comment by erkgmz** [comment]
This is a content update in Wordpress and should be fixed now. Please check @CristianStrit

**Comment by CristianStrit** [comment]
Ok

**Comment by erkgmz** [comment]
@CristianStrit please review this again. Close this Issue once you've confirmed the fix.
