### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by CristianStrit** [TastingKitchen/tasting-kitchen#18]
Footer should have new icons – will send that in separate email.
TASTING KITCHEN in logo, bottom left-hand corner, should be written out in **Inter Medium**. 

<img width="961" alt="Screen Shot 2020-06-29 at 11 43 57 PM" src="https://user-images.githubusercontent.com/67622271/86092666-b1286f80-ba62-11ea-87cb-2f95d6276a1f.png">

**Comment by erkgmz** [comment]
Font weight issues will be addressed in the next PR. I'll update icons once i get them from you.
