### ISSUE TITLE
Single article component

### ISSUE THREAD

**Issue by CristianStrit** [TastingKitchen/tasting-kitchen#21]
Please revise typography styles and colors 

<img width="982" alt="Screen Shot 2020-06-30 at 12 36 45 AM" src="https://user-images.githubusercontent.com/67622271/86098621-3c0d6800-ba6b-11ea-8214-72077f8f29f5.png">
for this component

**Comment by erkgmz** [comment]
@CristianStrit can you call out the specific issues? 

I see a different color on mobile and tablet
https://projects.invisionapp.com/d/main?origin=v7#/console/19715154/412339060/inspect?scrollOffset=635
https://projects.invisionapp.com/d/main?origin=v7#/console/19631646/410477194/inspect?scrollOffset=635

And on desktop I see a gray
https://projects.invisionapp.com/d/main?origin=v7#/console/19625795/413451257/inspect?scrollOffset=467.5

**Comment by CristianStrit** [comment]
the reason is that on desktop you have a rollover state that turns the copy black on rollover, on tablet and mobile you dont have rollover

**Comment by erkgmz** [comment]
What triggers the rollover state? A hover over the copy or over the entire section?

**Comment by erkgmz** [comment]
@CristianStrit got it, Ill apply the rollover to the copy.
