### ISSUE TITLE
Responsive article hero component

### ISSUE THREAD

**Issue by CristianStrit** [TastingKitchen/tasting-kitchen#29]
The tile section on the article hero component is getting distorted under 1440PX. The expected behavior is that the container box retains its size until the tablet breakpoint.

Bellow is a screenshot of the current development:
<img width="1402" alt="Screen Shot 2020-06-30 at 3 31 25 PM" src="https://user-images.githubusercontent.com/67622271/86183615-466d4780-bae7-11ea-8ab3-9eaa38157706.png">

Here is the container size on large viewports from 835 to 1440 and up
<img width="851" alt="Screen Shot 2020-06-30 at 3 38 06 PM" src="https://user-images.githubusercontent.com/67622271/86183833-b8de2780-bae7-11ea-9dfb-c24530fc0a48.png">

**Comment by erkgmz** [comment]
@CristianStrit not sure I understand what the issue with tablet is. Here is the mockup in Invision
![image](https://user-images.githubusercontent.com/8197799/86186260-715a9a00-baed-11ea-99d7-9f1a8dac8580.png)

The block is 4 columns wide on large breakpoints, this seems correct to me. See the Invision here https://projects.invisionapp.com/d/main?origin=v7#/console/19715154/412407584/preview?scrollOffset=2213.75

Let me know if you have any problems viewing that link.

**Comment by erkgmz** [comment]
Will be solved with #33
