### ISSUE TITLE
Hero component & columns - adjust width under 1440

### ISSUE THREAD

**Issue by erkgmz** [TastingKitchen/tasting-kitchen#33]
Use 1440 breakpoint down to 1024 hero component where title sits & copy column

**Comment by erkgmz** [comment]
@CristianStrit this looks off to me... can you confirm this is how you want it to look on 1024?

![image](https://user-images.githubusercontent.com/8197799/86201845-73385380-bb15-11ea-8138-128992e876ef.png)

**Comment by CristianStrit** [comment]
No, this is not right. Can we have this to be responsive as you had it from 1024 and below, on 1025 lock the size of the copy and the container to be 875px width. At 1025 we reach the maximum size of the container and copy width and we lock it beyond 1025 px.

**Comment by erkgmz** [comment]
Hey @CristianStrit Im a little worried about stepping out of the boundaries of our current breakpoints (375 > 834 > 1024 > 1440) which will introduce hacks. 

It sounds like this is more of an enhancement and not a bug. How about we revisit after we resolve more of these other issues?
