### ISSUE TITLE
Hero Title Section Size and Typography

### ISSUE THREAD

**Issue by CristianStrit** [TastingKitchen/tasting-kitchen#7]
The box that contains the article name and description is not accurate to the design. Please refer to invision link for correct Size, typography color styles and design elements.

<img width="1501" alt="Screen Shot 2020-06-29 at 10 23 06 PM" src="https://user-images.githubusercontent.com/67622271/86086941-ca77ee80-ba57-11ea-8a8d-731ffd4b3aa0.png">

**Comment by TastingKitchen** [comment]
@CristianStrit the mockups in Invision vary, will you provide the URL to the specific mock up you are referring to?

**Comment by erkgmz** [comment]
@CristianStrit the mockups in Invision vary, will you provide the URL to the specific mock up you are referring to?

**Comment by CristianStrit** [comment]
https://projects.invisionapp.com/d/main?origin=v7#/console/19625795/412330104/preview?scrollOffset=521

These things should not vary, I had gone through these to make sure these are all the same specs.

**Comment by erkgmz** [comment]
- Maxed out copy width to 634px (from Invision)
- Increased headline weight to 500 (Invision only says "SemiBold" and not sure exactly what means in terms of an actual value)
- Changed the copy color from black to #282828
- I increased the width of the horizontal on 1024+ to 146px (from Invision) and changed the background color

**Comment by erkgmz** [comment]
These updates will be on the next PR
