### ISSUE TITLE
two column copy max size

### ISSUE THREAD

**Issue by CristianStrit** [TastingKitchen/tasting-kitchen#8]
The two column copy max column width size should be Width: 418px

<img width="968" alt="Screen Shot 2020-06-29 at 10 33 48 PM" src="https://user-images.githubusercontent.com/67622271/86087269-a668dd00-ba58-11ea-921d-f9654544a371.png">

The color of the copy and the typography style should be:
color: #282828;
font-family: "Libre Baskerville";
font-size: 12px;
line-height: 18px;

**Comment by erkgmz** [comment]
@CristianStrit

Typography will be updated in my next PR.

On your note about "max-width", most components are using a 6 column grid with a 40px gap, per your grid guide in Sketch and Invision. These columns are taking up 2 columns. I think we should leave it as is to keep it consistent with the grid. They will stop growing when the site maxes out at 1920. Maybe we should reduce the sites max width instead? 

What do you think?
